apiVersion: v1
kind: Service
metadata:
  name: epoch-api-lb
  namespace: epoch-api
  labels:
    app: epoch-api-app
spec:
  type: LoadBalancer
  ports:
  - port: 9000
    targetPort: 8080
  selector:
    app: epoch-api-app
